### ISSUE TITLE
Fix responsive layout 

### ISSUE THREAD

**Issue by jtreanor** [jtreanor/SummerCourses#23]

**Comment by bao-qian** [comment]
![fix_responsive_bug](https://f.cloud.github.com/assets/1169912/203351/e446a1b8-8133-11e2-8695-f3f8f917f792.png)

**Comment by bao-qian** [comment]
Accoring to bootstrap ![official guide](http://twitter.github.com/bootstrap/components.html#navbar)

> Add .navbar-fixed-top and remember to account for the hidden area underneath it by adding at least 40px padding  to the <body>. Be sure to add this after the core Bootstrap CSS and before the optional responsive CSS.

We need the margin.
After insect source code of bootstrap official site, I found that they don't set the margin on body directly. They add <header></header>  between nav-bar div and container div.

``` html
<div class="navbar navbar-inverse navbar-fixed-top">
<header id="overview" class="jumbotron subhead">
<div class="container">
```

And set the margin of <heade> instead of <body>.
Everything seems works fine on my local machine.

**Comment by bao-qian** [comment]
One more question is what is this part of code used for?

``` bash
SummerCourses / app / assets / stylesheets / custom.css.scss
```

``` css
.navbar .brand {
  padding: 5px 25px 5px;
}
```

**Comment by bao-qian** [comment]
@jtreanor

**Comment by jtreanor** [comment]
This code is to position the UCC logo correctly on the nav bar.

That fix looks good. You can close this once it is pushed.
